import {OpportunityLogModel} from './opportunityLog.model';
import {OrderModel} from './order.model';
import {ItemOpportuinityModel} from './opportunity.model';

export class LeadModel {
  address: string;
  advertisingSource: string;
  age: number;
  birthday: string;
  contactStatus: number;
  contactStatusName: string;
  createdBy: string;
  createdOn: string;
  customerId: number;
  dateOfBirth: string;
  description: string;
  email: string;
  facebook: string;
  firstName: string;
  fullName: string;
  gender: number;
  id: number;
  items: ItemOpportuinityModel[];
  lastName: string;
  logs: OpportunityLogModel[];
  modifiedBy: string;
  modifiedOn: string;
  oppSource: number;
  oppSourceName: string;
  opportunityCreatedDate: string;
  orders: OrderModel[];
  pendingToDate: string;
  phone: string;
  processStatus: number;
  promotionCode: string;
  provinceCode: any;
  rating: null;
  source: number;
  sourceName: string;
  status: number;
  statusName: string;
  stt?: number;
  subDistrictCode: any;
  tags: any = [];
  ticketClassify: string;
  userId: number;
  userName: string;
  users: any = [];
  website: string;
  works: any = [];
  districtCode: any;
}
